# Soporte - Sistemas Ursol S.A.
# Costa Rica | 30 años de experiencia tecnológica
# Contacto: sistemas@ursol.com | WhatsApp +506 8868-7765

custom: 
  - https://ursol.com
  - https://ursol.net
  - https://sites.google.com/view/repdevursol/home/repositorio
