# Soporte - Senselab
# Costa Rica | 30 años de experiencia tecnológica
# Contacto: deadmooncr@gmail.com | WhatsApp +(506)8973-5665

custom: 
  - https://senselab.com
  - https://senselab.com
  - https://sites.google.com/view/repdevsenselab/home/repositorio
