<?php

namespace Tests\Contract\Provider;

use PhpPact\Standalone\ProviderVerifier\Model\Config\ProviderTransport;
use PhpPact\Standalone\ProviderVerifier\Model\VerifierConfig;
use PhpPact\Standalone\ProviderVerifier\Verifier;
use PHPUnit\Framework\TestCase;

/**
 * Provider verification test.
 *
 * Verifies that the Ursol CAST API provider satisfies
 * all consumer contracts generated by the consumer tests.
 *
 * Prerequisites:
 *   1. Run consumer tests first to generate pact files:
 *      php artisan test tests/Contract/Consumer/
 *   2. Start the API server:
 *      php artisan serve --port=8080
 *   3. Run this test:
 *      php artisan test tests/Contract/Provider/
 *
 * In CI, the API server is started automatically before verification.
 */
class UrsolCastApiVerificationTest extends TestCase
{
    public function testPactVerifyConsumerContracts(): void
    {
        $config = new VerifierConfig();
        $config->getProviderInfo()
            ->setName('UrsolCastApi')
            ->setHost('127.0.0.1')
            ->setPort((int) ($_ENV['PACT_PROVIDER_PORT'] ?? 8080))
            ->setScheme('http');

        // State change URL — handles provider state setup
        $stateChangeUrl = sprintf(
            'http://127.0.0.1:%d/pact/provider-states',
            (int) ($_ENV['PACT_PROVIDER_PORT'] ?? 8080)
        );
        $config->getProviderState()
            ->setStateChangeUrl(new \GuzzleHttp\Psr7\Uri($stateChangeUrl))
            ->setStateChangeTeardown(true)
            ->setStateChangeAsBody(true);

        $verifier = new Verifier($config);

        $pactDir = dirname(__DIR__) . '/pacts';

        if (is_dir($pactDir)) {
            $verifier->addDirectory($pactDir);
        } else {
            $this->markTestSkipped(
                'No pact files found. Run consumer tests first: php artisan test tests/Contract/Consumer/'
            );
        }

        // Check that the provider server is reachable before attempting verification
        $providerPort = (int) ($_ENV['PACT_PROVIDER_PORT'] ?? 8080);
        $connection = @fsockopen('127.0.0.1', $providerPort, $errno, $errstr, 2);
        if (!$connection) {
            $this->markTestSkipped(
                "Provider server not running on port {$providerPort}. Start with: php artisan serve --port={$providerPort}"
            );
        }
        fclose($connection);

        $this->assertTrue($verifier->verify(), 'Pact verification failed. Check provider implementation matches consumer expectations.');
    }
}
