apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ursol-cast-storage-pvc
  namespace: ursol-cast
  labels:
    app.kubernetes.io/name: ursol-cast-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ursol-cast
  labels:
    app.kubernetes.io/name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: ursol-cast
  labels:
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
