apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: senselab-core-storage-pvc
  namespace: senselab-core
  labels:
    app.kubernetes.io/name: senselab-core-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: senselab-core
  labels:
    app.kubernetes.io/name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: senselab-core
  labels:
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
