apiVersion: v1
kind: Service
metadata:
  name: senselab-core-api-service
  namespace: senselab-core
  labels:
    app.kubernetes.io/name: senselab-core-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: senselab-core-api
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: senselab-core
  labels:
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: senselab-core
  labels:
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
